name: Java CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATASOURCE_URL: jdbc:h2:mem:testdb
      DATASOURCE_USER: sa
      DATASOURCE_PASSWORD: ""
      DATASOURCE_DRIVER: org.h2.Driver

      GOOGLE_USERNAME: email
      JWT_SECRET: test-secret
      OAUTH_CLIENT_ID: dummy-client-id
      CLIENT_SECRET: dummy-client-secret
      SCOPE: profile,email

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and Test with Maven
        run: mvn -B clean install
